name: Frontend-CI

on:
  workflow_dispatch: 
  push: 
    branches:   
      - main
        
jobs:   
  set_environment:    
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Docker Build
        id: set_env
        run: 
          docker build -t appservicedeployment:latest .
      - name: Trivy Scan
        run: 
          trivy image --severity "HIGH,CRITICAL" --vuln-type "os,library" --exit-code "0" githubcisharnidemo.azurecr.io/demoenv:${{ github.run_id }}
          
      - name: azure container registry
        run: |
          docker login sharnidemo.azurecr.io -u sharnidemo -p ${{ secrets.TOKEN }}
          docker push sharnidemo.azurecr.io/demoenv:${{ github.run_id }} 
          
    outputs:
      environment: ${{ env.environment }}
