name: Frontend-CI

on:
  workflow_dispatch: 
  push: 
    branches:   
      - nonroot
        
jobs:   
  set_environment:    
    runs-on: ubuntu-latest
    # needs: demo 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Docker Build
        id: set_env
        run: 
          docker build -t appservicedeployment:latest .
          
    outputs:
      environment: ${{ env.environment }}
